[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { x = 20, y = 20 }

decorations = "Buttonless"
opacity = 0.92
blur = true

[scrolling]
history = 10000

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 18.0
